### ISSUE TITLE
User Story 8: Persist Favorites and Comments in the Browser

### ISSUE THREAD

**Issue by kisp** [KutlualpTazefidan/art-gallery-app#10]
#### Value Proposition

**As an** art enthusiast

**I want to** persist my favorites and comments

**so that** the data will not be lost when I close the app.

#### Acceptance Criteria

- [ ] All favorite flags and comments added to art pieces are persisted across browser reloads

#### Tasks

- [ ] Install the package `use-local-storage-state`
- [ ] Use the `useLocalStorageState` hook to store the `artPiecesInfo` state

https://github.com/spiced-academy/fs-web-exercises/blob/main/sessions/recap-project-5/art-gallery-app/README.md#user-story-8-persist-favorites-and-comments-in-the-browser
