### ISSUE TITLE
User Story 10 - bonus: Styling of the Art Gallery App

### ISSUE THREAD

**Issue by KutlualpTazefidan** [KutlualpTazefidan/art-gallery-app#23]
#### Value Proposition

**As an** art enthusiast

**I want to** see a artistically nice pages

**so that** I can be inspired to do more creative work.

#### Acceptance Criteria

- [x] Styling for the spotlight/main page 
- [x] Styling for the art-pieces page
- [x] Styling for the details page
- [x] Styling for the favorites page

#### Tasks

- [x] Use a styled component for the `Navigation` bar
- [x] Use a styled component for the "ArtPreview" component
- [x] Use a styled component for the `Spotlight` page to highlight a random piece
- [x] Use a styled component for the `Art-Pieces` page
- [x] Use a styled component for the `Details` page
- [x] Change font style
- [x] Smooth transitions between pages
- [ ] Animate background
