### ISSUE TITLE
User Story 7: Comments for Art Pieces

### ISSUE THREAD

**Issue by kisp** [KutlualpTazefidan/art-gallery-app#9]
#### Value Proposition

**As an** art enthusiast

**I want to** write comments for art pieces

**so that** I can note my ideas regarding the work.

#### Acceptance Criteria

- [x] The detail view has a list of comments for this art piece with the headline "Comments" 🖼️
- [x] Each comment's text is displayed 🖼️
- [x] Each comment's date and time is displayed 🖼️
- [x] The detail view has an input field to write a comment 🖼️
- [x] The detail view has a submit button labeled "Send" 🖼️
- [x] After submitting the form, the comment is appended to the list of comments 🖼️

#### Tasks

- [x] Store comments per art piece in the `artPiecesInfo` state
- [x] Create a `CommentForm` component
- [x] `CommentForm` props: `onSubmitComment`
- [x] Create a `Comments` components
- [x] `Comments` props: `comments`
- [x] All acceptance criteria marked with 🖼️ are covered by component testing

https://github.com/spiced-academy/fs-web-exercises/blob/main/sessions/recap-project-5/art-gallery-app/README.md#user-story-7-comments-for-art-pieces
